spring:
  application:
    name: gkh-gateway
  # 服务注册与发现
  cloud:
    nacos:
      discovery:
        server-addr: 106.54.215.151:8848
        namespace: 3118b88b-9862-4fcc-8e53-7f291c16ba50
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: lb://gkh-user
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=2
            - id: resource-service
              uri: lb://gkh-resource
              predicates:
                - Path=/resource/**
              filters:
                - StripPrefix=2

server:
  port: 17000
  servlet:
    context-path: /api
