spring:
  application:
    name: gkh-resource
  cloud:
    nacos:
#      server-addr: 106.54.215.151:8848
#      config:
#        namespace: 3118b88b-9862-4fcc-8e53-7f291c16ba50
      discovery:
        server-addr: 106.54.215.151:8848
        namespace: 3118b88b-9862-4fcc-8e53-7f291c16ba50

server:
  port: 17002

minio:
  endpoint: http://106.54.215.151:9000
  access-key: root
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: muse-ai

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.edu.sxu.gkhuser.controller
  default-flat-param-object: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

